### ISSUE TITLE
Handle gmail_quote div in emails created by clicking the Reply button in gmail

### ISSUE THREAD

**Issue by jeremyschlatter** [mailgun/talon#20]
If you click "reply" in gmail, and then change the subject line and undo the quotation in the WYSIWYG editor, you get something that looks a lot like a fresh email that you just typed yourself. If you send the email to another gmail user, it will render for them the way you would expect if you composed the email yourself from scratch.

But gmail wraps the content in a `<div class="gmail_quote">`, which gets stripped by `quotations.extract_from_html`. Ideally, talon would know when this was the case and not treat the div as a quote. This seems hard, though. It's not clear to me how to identify this case.

**Comment by obukhov-sergey** [comment]
@fiatjaf this one should be fixed. At least for Gmail. The edge case @jeremyschlatter found aside - not sure how we could fight this one. It will be solved when we stop looking for html tags completely and improve on ``html to text, strip text quotations, remove corresponding html tags`` algo.

So far I just made a change not to handle ``<blockquote>`` as an indicator of quotations if it has ``gmail_quote``. Since Gmail uses ``divs`` with ``gmail_quote`` class to indicate quotations.
