### ISSUE TITLE
Failing Testcase

### ISSUE THREAD

**Issue by cyberhobo** [mailgun/talon#28]
Just in case it's helpful, we developed this test data based on a signature we received that wasn't parsed correctly. Here's the data I pasted at http://talon.mailgun.net/ to reproduce:

```
From: <testbot.maton@companysdomain.com>
To: <person@serverboxen.com>
Subject: Re: [SPF] Still trying to figure out your signature
Date: Tue, 16 Dec 2014 16:46:22 +0000
Message-Id: <D0B5BDE2.882AA%testbot.maton@companysdomain.com>
Accept-Language: en-US, ja-JP
Content-Language: en-US
User-Agent: Microsoft-MacOutlook/14.4.6.141106
Content-Type: multipart/alternative; boundary="_000_D0B5BDE2882AAtestbotmatoncompanysdomaincom_"
Mime-Version: 1.0
Sender: testbot.maton=companysdomain.com@serverboxen.com
 
--_000_D0B5BDE2882AAtestbotmatoncompanysdomaincom_
Content-Type: text/plain; charset="us-ascii"
Content-Transfer-Encoding: quoted-printable
 
Sure thing - happy to help! Hope you can get it sorted out :)
-----
Testbot Maton
Manager, Communications Platforms
Company Liner
 
Phone: +1 555.555.5555
Mobile: +1 555.555.5555
 
testbot.maton@companysdomain.com<mailto:testbot.maton@companysdomain.com>
http://companysdomain.com<http://companysdomain.com/>

```

**Comment by obukhov-sergey** [comment]
Hi @cyberhobo. Thanks for reporting it. The signature wasn't parsed correctly (only the last line was extracted) because the previous line is too long. We have a sanity check that doesn't consider lines longer than 60 chars (and anything coming before it) to be a signature. Most signature lines are shorter than 60 chars and this check while not 100% accurate saves us (and possibly you) a lot of false positives.
