### ISSUE TITLE
Pip install fails

### ISSUE THREAD

**Issue by EugeneFeshchenko** [mailgun/talon#40]
When I install talon via pip from pypi is installs fine. But in this case it's not installing PyML and it's separate installation also fails.
So I decided to install latest version of talon from github and here is what I got:
https://gist.github.com/EugeneFeshchenko/6335f648838842209a00
I was trying to install it in a newly created env.

Is it me doing something wrong or setup file needs fixing ?

Also in general, installation process is not very obvious:
When you install from pypi you have to install PyML separately
When you install from github PyML install as well 
I didn't find info that numpy should be preinstalled in order to install PyMl but it's doc says numpy is required.

**Comment by Alex3917** [comment]
I was successful at getting it to install on ubuntu by doing the following:

1) Install numpy: `pip install numpy`

2) Install the packages needed to install lxml, which is a dependency of PyML.  On ubuntu this can be done as follows: ` sudo apt-get install libxml2-dev libxslt-dev python-dev`

3) Download and install PyML: 

```
curl -L http://sourceforge.net/projects/pyml/files/latest/download?source=typ_redirect > PyML.tar.gz;
tar -xzf PyML.tar.gz && cd PyML-* && python setup.py build && python setup.py install && rm -rf PyML.tar.gz; 
```

4) Install Talon: `pip install talon`

Also, you're trying to install talon inside a vagrant environment, you need to increase the amount of memory available to virtualbox to at least 1024mb in order to get PyML to install. You can do this by adding these lines to the end of  your vagrant file:

```
config.vm.provider "virtualbox" do |v|
    v.memory = 1024
    v.cpus = 2
end
```

**Comment by AlexRiina** [comment]
Give my pull request a try if you are still interested.

**Comment by obukhov-sergey** [comment]
Hi @AlexRiina, thanks for the PR! I've merged it and updated PyPi
